#!/bin/sh

pandoc -s --toc --toc-depth=1 --number-sections --number-offset=0 --top-level-division=chapter --filter myfilter.js --filter  ~/.cabal/bin/pandoc-include-code *.md -f markdown -t html -c cj.css > index.html
